<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        padding: 50
        spacing: 20

        Button:
            text: "Hello Wordl!"
        
        Button:
            text: "Goodbye Wordl!"

        Button:
            text: "j'ai faim!"
            pos_hint: {'center_x': 0.5}
            size_hint: (0.5,0.5)
            #size_hint: (None,None)
            #width: 100
            #height: 20