<DEMO1>:
    MDLabel:
        text: 'ECRAN1'
        halign: "center"
    MDRaisedButton:
        text: "Aller a ecran 2"
        pos_hint: {"center_y": .6, "center_x": .5}
        on_release: root.manager.current = "DEMO2"

<DEMO2>:
    MDLabel:
        text: 'ECRAN2'
        halign: "center"
    MDRaisedButton:
        text: "Aller a ecran 1"
        pos_hint: {"center_y": .6, "center_x": .5}
        on_release: root.manager.current = "DEMO1"

    